# -*- coding: utf-8 -*-
"""task2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17eFnyNOguFsMs7ZhkxhUgomIxBZBJerZ
"""

# Union-Find
class UnionFind:
    def __init__(self, vertices):
        self.parent = {v: v for v in vertices}

    def find(self, v):
        if self.parent[v] != v:
            self.parent[v] = self.find(self.parent[v])  # directly map the vertex to its root
        return self.parent[v]

    def union(self, v1, v2):
        root1 = self.find(v1)
        root2 = self.find(v2)
        if root1 != root2:
            self.parent[root2] = root1

# Example usage:
vertices = ['A', 'B', 'C', 'D']
uf = UnionFind(vertices)

uf.union('A', 'B')
uf.union('C', 'D')

print(uf.find('A'), uf.find('B'))  # same root
print(uf.find('C'), uf.find('D'))  # same root
print(uf.find('A'), uf.find('C'))  # different sets