# -*- coding: utf-8 -*-
"""Task1.Miniproject

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12OBsB2QxY3dygi-fDJRXKXgEnV1UkK8J
"""

# -----------------------------------------
# Minimum Cost Network Builder using Kruskal’s Algorithm
# -----------------------------------------

class DisjointSet:
    def __init__(self, vertices):
        self.parent = {v: v for v in vertices}
        self.rank = {v: 0 for v in vertices}

    def find(self, item):
        if self.parent[item] != item:
            self.parent[item] = self.find(self.parent[item])  # Path compression
        return self.parent[item]

    def union(self, set1, set2):
        root1 = self.find(set1)
        root2 = self.find(set2)

        if root1 != root2:
            # Union by rank
            if self.rank[root1] < self.rank[root2]:
                self.parent[root1] = root2
            elif self.rank[root1] > self.rank[root2]:
                self.parent[root2] = root1
            else:
                self.parent[root2] = root1
                self.rank[root1] += 1


def kruskal(vertices, edges):
    """
    vertices: list of vertices
    edges: list of tuples (u, v, weight)
    """
    # Step 1: Sort all edges in non-decreasing order of weight
    edges.sort(key=lambda x: x[2])

    # Step 2: Create a disjoint set for vertices
    ds = DisjointSet(vertices)

    mst_edges = []
    total_cost = 0

    # Step 3: Iterate through sorted edges
    for u, v, w in edges:
        # Check if including this edge causes a cycle
        if ds.find(u) != ds.find(v):
            ds.union(u, v)
            mst_edges.append((u, v, w))
            total_cost += w

    return mst_edges, total_cost


# -----------------------------------------
# Example Usage
# -----------------------------------------
if __name__ == "__main__":
    vertices = ['A', 'B', 'C', 'D']
    edges = [
        ('A', 'B', 1),
        ('A', 'C', 3),
        ('B', 'C', 1),
        ('B', 'D', 4),
        ('C', 'D', 2)
    ]

    mst, cost = kruskal(vertices, edges)

    print("\nEdges in Minimum Cost Network (MST):")
    for u, v, w in mst:
        print(f"{u} -- {v} == {w}")

    print(f"\nTotal Minimum Cost of Network: {cost}")